# Generated by Django 4.1.7 on 2023-02-17 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userbankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounttype',
            name='interest_calculation_per_year',
            field=models.IntegerField(help_text='The number of times interest will be calculated per year', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
